services:
  - type: web
    name: lucky-jet-autonomous-engine
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        value: "8996586274:AAEmM5lqjgc6FwDErYt69CwqSqOCPGPSDzw"
      - key: CHAT_ID
        value: "6551286352"
      - key: PORT
        value: 3000
